name: "Micrometer Release Docker Action"
description: "A GitHub Action that runs a Java application using Docker to do release / post release tasks"
author: "micrometer.io team"

inputs:
  gh_token:
    description: "GitHub Token for authentication"
    required: true
  changelog_generator_version:
    description: "Spring GitHub Changelog Generator version (https://github.com/spring-io/github-changelog-generator/)"
    required: false
    default: ""
  github_repository:
    description: "GitHub repository (auto-detected from build)"
    required: false
    default: ${{ github.repository }}
  previous_ref_name:
    description: "[SINGLE PROJECT] Previous release version in this train (e.g.v1.14.8)"
    required: false
    default: ""
  context_propagation_versions:
    description: "[TRAIN] Comma separated list of context propagation versions (e.g. 1.0.0,1.1.0,1.1.0)"
    required: false
    default: ""
  micrometer_versions:
    description: "[TRAIN] Comma separated list of micrometer versions (e.g. 1.13.2,1.14.8,1.15.9)"
    required: false
    default: ""
  tracing_versions:
    description: "[TRAIN] Comma separated list of context micrometer tracing versions (e.g. 1.5.0,1.6.0,1.7.0)"
    required: false
    default: ""
  docs_gen_versions:
    description: "[TRAIN] Comma separated list of context micrometer docs generator versions (e.g. 1.0.0,1.1.0,1.2.0)"
    required: false
    default: ""
  spring_release_gchat_webhook_url:
    description: "URL to GChat to post notifications about the release"
    required: false
  bluesky_handle:
    description: "Bluesky handle where release notification will be posted"
    required: false
  bluesky_password:
    description: "Bluesky handle password"
    required: false
  circle_ci_token:
    description: "Circle CI Token to query for build status"
    required: false

outputs: {}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GH_TOKEN: ${{ inputs.gh_token }}
    CHANGELOG_GENERATOR_VERSION: ${{ inputs.changelog_generator_version }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    PREVIOUS_REF_NAME: ${{ inputs.previous_ref_name }}
    SPRING_RELEASE_GCHAT_WEBHOOK_URL: ${{ inputs.spring_release_gchat_webhook_url }}
    BLUESKY_HANDLE: ${{ inputs.bluesky_handle }}
    BLUESKY_PASSWORD: ${{ inputs.bluesky_password }}
    CIRCLE_CI_TOKEN: ${{ inputs.circle_ci_token }}
    CONTEXT_PROPAGATION_VERSIONS: ${{ inputs.context_propagation_versions }}
    MICROMETER_VERSIONS: ${{ inputs.micrometer_versions }}
    TRACING_VERSIONS: ${{ inputs.tracing_versions }}
    DOCS_GEN_VERSIONS: ${{ inputs.docs_gen_versions }}

branding:
  icon: "activity"
  color: "green"
