name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/setup-and-run-build

  acceptanceTests:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Don't run for PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run e2e tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_TEST_PROJECT }}
        run: ./gradlew e2e
