name: Release Train (for a single project)

on:
  workflow_dispatch:
    inputs:
      context_propagation_versions:
        description: "[TRAIN] Comma separated list of context propagation versions (e.g. 1.0.0,1.1.0,1.1.0)"
        required: false
        default: ""
      micrometer_versions:
        description: "[TRAIN] Comma separated list of micrometer versions (e.g. 1.13.2,1.14.8,1.15.9)"
        required: false
        default: ""
      tracing_versions:
        description: "[TRAIN] Comma separated list of micrometer tracing versions (e.g. 1.5.0,1.6.0,1.7.0)"
        required: false
        default: ""
      docs_gen_versions:
        description: "[TRAIN] Comma separated list of micrometer docs generator versions (e.g. 1.0.0,1.1.0,1.2.0)"
        required: false
        default: ""

jobs:
  post_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Post Release Tasks
        uses: micrometer-metrics/micrometer-github-workflows@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          spring_release_gchat_webhook_url: ${{ secrets.SPRING_RELEASE_GCHAT_WEBHOOK_URL }}
          bluesky_handle: ${{ secrets.BLUESKY_HANDLE }}
          bluesky_password: ${{ secrets.BLUESKY_PASSWORD }}
          context_propagation_versions: ${{ github.event.inputs.context_propagation_versions }}
          micrometer_versions: ${{ github.event.inputs.micrometer_versions }}
          tracing_versions: ${{ github.event.inputs.tracing_versions }}
          docs_gen_versions: ${{ github.event.inputs.docs_gen_versions }}
          meta_release_enabled: true
